const TransactionData = [
  {
    id: 1488,
    category: 'foodAndDrinks',
    transactionType: 'income',
    currency: 'USD',
    amount: 146,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:44',
    note: '123'
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'Expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'Expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'Expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
  {
    id: 1488,
    category: 'foodAndDrinks',
    transactionType: 'Income',
    currency: 'USD',
    amount: 145,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:44',
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'Expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
  {
    id: 1488,
    category: 'foodAndDrinks',
    transactionType: 'Income',
    currency: 'USD',
    amount: 145,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:44',
  },
  {
    id: 1488,
    category: 'foodAndDrinks',
    transactionType: 'Income',
    currency: 'USD',
    amount: 145,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:44',
  },
  {
    id: 1488,
    category: 'foodAndDrinks',
    transactionType: 'Income',
    currency: 'USD',
    amount: 145,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:44',
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'Expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'Expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'Expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
  {
    id: 1489,
    category: 'foodAndDrinks',
    transactionType: 'Expense',
    currency: 'USD',
    amount: 120,
    place: 'Vodafone',
    date: '2024-11-05',
    time: '23:40',
  },
];

export default TransactionData;